---
title: "Sebastian G. Mutz, Dr. rer. nat. habil."
---

# <span style="color:#38967c"> Basic Information </span>

::: columns
::: {.column width="50%"}

#### Institute

| | |
| :- | :---- |
| Position | Senior Lecturer (Associate Professor) |
| Affiliation | School of Geographical and Earth Sciences, University of Glasgow, UK |
:::

::: {.column width="5%"}
:::

::: {.column width="45%"}

#### Web

| | |
| :- | :---- |
| ORCID | [0000-0001-8180-6150](https://orcid.org/0000-0001-8180-6150) |
| GitHub | [@sebastian-mutz](https://github.com/sebastian-mutz) |
| LinkedIn | [Sebastian Gerhard Mutz](https://www.linkedin.com/in/sebastian-gerhard-m-5b9952210/) |
| University | [UofG staff profile](https://www.gla.ac.uk/schools/ges/staff/sebastianmutz/) |
| Personal | [sebastianmutz.eu](https://sebastianmutz.eu/) |
| Research lab | [mutz.science](https://mutz.science/) |
| E-mail | [sebastian.mutz@glasgow.ac.uk](mailto:sebastian.mutz@glasgow.ac.uk) |

:::
:::







# <span style="color:#38967c"> Academic Qualifications </span>

| Year of Award | Qualification | Institute |
| :-- | :---- | :---- |
| 2023 | Habilitation | University of Tübingen, Germany |
| 2015 | Doctorate (Dr. rer. nat.) | University of Würzburg, Germany |
| 2008 | Integrated Master (M.Geol.) | University of Leicester, UK |




# <span style="color:#38967c"> Positions </span>

| Year | Position | Institute |
| :-- | :---- | :---- |
| 2023 -- | Senior Lecturer (Associate Professor) | University of Glasgow, UK |
| 2016 -- 2023 | Akademischer Rat (Assistant Professor) | University of Tübingen, Germany |
| 2014 -- 2016 | Postdoctoral Researcher | University of Tübingen, Germany |
| 2012 | Postdoctoral Researcher | University of Tübingen, Germany |
| 2008 -- 2012 | Research Associate | University of Würzburg, Germany |




# <span style="color:#38967c"> Research Grants and Awards </span>

| Year | Topic | Type | Funder | Duration | Status |
|:- | :------ |:--- | :-- | :-- | :-- |
| 2025 | RainX -- Modelling Rainfall Extremes | PhD Project | NERC | 3.5 years | ongoing |
| 2024 | ExaGEO -- Exascale Computing for the Environment | Doctoral Training Programme | NERC | 5 years | ongoing |
| 2024 | GECO-21 -- Glacial Ecology | Research Support | NERC | 1+ years | ongoing |
| 2020 | REAL -- Alps Climate and Uplist History | PhD Project | DFG | 3 years | completed |
| 2020 | Open-Access Climate Education (Higher Education Teaching Grant) | Teaching Support | EGU | 1 years | completed |
| 2017 | QTiP -- Tibetan Plateau History | Postdoc Project | BMBF | 3 years | completed |
| 2017 | APE -- Alps Climate and Uplist History | Postdoc Project | DFG | 3 years | completed |
| 2016 | Earthquake Education (Public Engagement Grant) | Outreach Support | EGU | 1 years | completed |




# <span style="color:#38967c"> Teaching and Supervision </span>

## Supervision

| Type | Number | Comment |
| :-- | :- | :---- |
| Postdoctoral Researcher | 2 | University of Tübingen(2) |
| Doctoral Student | 2 | University of Glasgow(1), University of Tübingen(1) |
| Master Student (Research) | 14 | University of Glasgow(1), University of Tübingen(13) |
| Master Student (Taught) | 13 | University of Glasgow(13) |
| Bachelor Student | 11 | University of Glasgow(8), University of Tübingen(3) |

**Note**: Only significant contributions to supervision are listed. Student details are not provided for privacy reasons.

## Taught Courses

### University of Glasgow

| Year | Course | Level | Language | Role |
| :- | :---- | :- | :- | :--- |
| 2025 | Theoretical and Applied Climatology | MSc | EN, Python, Fortran | Developer, coordinator, instructor |
| 2025 | Global Challenges (climate block) | MSc | EN | Co-developer, instructor |
| 2025 | Geography 2 (physical climatology block) | 2 | EN | Developer, instructor |
| 2025 | Introduction to Climate Change and Sustainability | All | EN | Co-developer, instructor |
| 2025 | Graduate Futures Work Placement | MSc | EN | Co-coordinator |
| 2024 | Theoretical and Applied Climatology | MSc | EN, Python | Developer, coordinator, instructor |
| 2024 | Global Challenges (climate lecture) | MSc | EN | Developer, instructor |
| 2024 | Geography 2 (physical climatology block) | 2 | EN | Developer, instructor |
| 2024 | Introduction to Climate Change and Sustainability | All | EN | Co-developer, instructor |
| 2024 | Geographical - Geological Field Course | 2 | EN | Instructor |
| 2023 | Introduction to Climate Change and Sustainability | All | EN | Co-developer, instructor |
| 2023 | Geomorphological Field Course | 2 | EN | Instructor |

### University of Tübingen

| Year | Course | Level | Language | Role |
| :- | :---- | :- | :- | :--- |
| 2022 | Physics of the Earth’s Surface | MSc | EN, Matlab | Co-developer, instructor |
| 2022 | Geological Mapping Course | BSc | DE, EN | Instructor |
| 2021 | Physics of the Earth’s Surface | MSc | EN, Matlab | Co-developer, instructor |
| 2021 | Geological Mapping Course | BSc | DE, EN | Instructor |
| 2020 | Applied Tectonics and Surface Processes | MSc | EN, Matlab | Co-developer, instructor |
| 2020 | Geological Mapping Course | BSc | DE, EN | Coordinator, instructor |
| 2019 | Applied Tectonics and Surface Processes | MSc | EN, Matlab | Co-developer, instructor |
| 2019 | Climate Dynamics, Probability and Statistics | MSc | EN, Matlab | Developer, coordinator, instructor |
| 2018 | Applied Tectonics and Surface Processes | MSc | EN, Matlab | Co-developer, instructor |
| 2018 | Geological Mapping Course | BSc | DE, EN | Coordinator, instructor |
| 2017 | Applied Tectonics and Surface Processes | MSc | EN, Matlab | Co-developer, instructor |
| 2017 | Geological Mapping Course | BSc | DE, EN | Instructor |
| 2016 | Applied Tectonics and Surface Processes | MSc | EN, Matlab | Co-developer, instructor |
| 2016 | Geological Mapping Course | BSc | DE, EN | Instructor |

### Invited Talks and Teaching

| Year | Course/Event | Institute |
| :- | :------ | :------ |
| 2025 | Communicating Uncertainty in Science (lecture) | University of Tübingen |
| 2023 | Colloquium (Earth system modelling) | University of Freiburg |
| 2021 | Colloquium (machine learning and climate science) | University of Tübingen |
| 2019 | Systemanalyse (lecture) | University of Tübingen |
| 2019 | Summer school (machine learning) | Karlsruhe Institute of Technology |
| 2016 | Scientific Instruments (lecture) | International Centre for Ethics in the Sciences and Humanities, Tübingen |
| 2015 | Colloquium | GfGD Annual Conference, Geological Society of London |
| 2014 | Colloquium | University of Tübingen |

# <span style="color:#38967c"> Service </span>

## Professional Societies and Development of Others

| Years | Project or Organisation | Role |
| :-- | :-- | :-- |
| 2025 | [Fortran-lang](https://fortran-lang.org/) at [Google Summer of Code](https://summerofcode.withgoogle.com/) | Mentor |
| 2024 -- | [Exascale Computing for Earth, Environmental, and Sustainability Solutions](https://www.exageo.org/) (ExaGEO) | Manager / Executive Committee Member |
| 2024 -- | [Earth System Modelling and Artificial Intelligence](https://sages.ac.uk/research/fora/earth-system-modelling-artificial-intelligence-esm-ai/) (SAGES) | Executive Committee Member |
| 2023 -- | [Earth System Dynamics](https://www.earth-system-dynamics.net/) Editorial Board | Associate Editor |
| 2022 -- | [Geoscience Communication](https://www.geoscience-communication.net/) Editorial Board | Associate Editor |
| 2022, 2023 | [EGU’s mentoring programme](https://www.egu.eu/outreach/mentoring/)| Mentor |
| 2018 -- | Professional Funding Bodies (e.g., Serrapilheira Institute) | Grant and Candidate Reviewer |
| 2009 -- | [European Geosciences Union](https://www.egu.eu/) | Member and Contributor (convener, reviewer, and more) |
| 2009 -- | Peer-Review Journals (e.g., *Geophysical Research Letters*, *Geoscientific Model Development*) | Article Reviewer |


## University Service (Only Recent)

| Years | Project or Organisation | Role |
| :-- | :-- | :-- |
| 2025 -- | [Climate and Environmental Science MSc](https://www.gla.ac.uk/postgraduate/taught/climateenvironmentalscience/) programme | Convener and Co-Developer |
| 2024 -- | [ExaGEO](https://www.exageo.org/) doctoral training programme | Manager and Co-Investigator |
| 2024 -- | *Maths/Stats meets GeoX*, interdepartmental initiative | Co-Leader |
| 2024 | Environmental Futures: Sustinable Systems MSc programme | Convener |




# <span style="color:#38967c"> Outreach </span>

## Service Roles

| Years | Project or Organisation | Role |
| :-- | :-- | :-- |
| 2024 -- | [EGU Outreach Committee](https://www.egu.eu/outreach/) | Member |
| 2024 -- | [EGU Teacher-Scientist Pairing Scheme](https://www.egu.eu/news/1205/egus-teacher-scientist-pairing-scheme-2025-apply-now-to-co-create-a-video-lesson-for-schools/) | Leader, Co-Developer |
| 2021 -- | [INTEGRATE Project](http://integrate.mutz.science) | Leader, Developer |
| 2015 -- | [ParsQuake NGO](https://parsquake.org/) | Member, Developer |


## In Press and Professional Blogs (Examples)

* 2022 - "Earth’s Climate is not in Equilibrium", *Spektrum (Germ. ed. Scientific American)* ([Read more](https://www.spektrum.de/news/palaeoklima-das-erdklima-ist-definitiv-nicht-im-gleichgewicht/2073378))
* 2021 - INTEGRATE: a complete higher-education teaching package for climate science ([Read more](https://blogs.egu.eu/geolog/2021/07/09/introducing-inetgrate-a-complete-higher-education-teaching-package-for-climate-science/))
* 2020 - "Lake to Desert to Lake", *Attempto!* ([Download](files/attempto_AppelMutz.pdf))
* 2016 - Exploring the Sustainable Development Goals at the University of Tübingen ([Read more](https://blogs.egu.eu/network/gfgd/2016/02/08/guest-blog-exploring-the-sustainable-development-goals-at-the-university-of-tubingen-germany/))

## Public Talks and Videos (Examples)

* 2022 - “On Climate Change, Climate Mitigation and the Prisoner's Dilemma", Reutlingen
* 2021 - Video for [GeoPark Maestrazgo](https://geoparques.es/en/portfolio_page/maestrazgo-en/), Producer
* 2021 - “Caught in the web of climate change: On melting, sliding and running away”, Reutlingen
* 2019 - [UN Forum on Science, Technology and Innovation, NY (USA)](https://drive.google.com/file/d/1rpEx8PtRWS38KoznPGlGt7k911X1WrmS/view), Co-author of GfGD statement

## Articles and Conference Abstracts

* 2021 - Using paired teaching for earthquake education in schools ([Read more](https://gc.copernicus.org/articles/4/281/2021/))
* 2021 - A blended learning approach to structural field mapping: combining local geology, virtual geology, and web-based tools ([Read more](https://doi.org/10.5194/egusphere-egu21-3581))
* 2020 - Paired teaching approach to earthquake education: a cross-country comparison between Dushanbe, Tajikistan and London, United Kingdom ([Read more](https://doi.org/10.5194/egusphere-egu2020-11230))




# <span style="color:#38967c"> Publications </span>


## Peer-Reviewed Articles

1. Boateng, D., Mutz, S. G., Methner, K., Ballian, A., Meijers, M. J.M., Mulch, A. and Ehlers, T. A. (2025) Refining paleoelevation estimates of the European Alps by simulating Middle Miocene climate and δ18O responses to diachronous surface uplift scenarios. Global and Planetary Change, 251, 104808. [https://doi.org/10.1016/j.gloplacha.2025.104808](https://doi.org/10.1016/j.gloplacha.2025.104808)

1. Guo, H., Pang, H., Wu, S., Xu, T., Mutz, S. G. , Zhan, Z., Lin, W., Zhang, W. and Hou, S. (2024) Global abnormal precipitation δ18O depletion during late/post monsoon season. Earth and Planetary Science Letters, 641, 118815. [https://doi.org/10.1016/j.epsl.2024.118815](https://doi.org/10.1016/j.epsl.2024.118815)

1. Boateng, D., Aryee, J. N.A., Baidu, M., Arthur, F. and Mutz, S. G. (2024) West African Monsoon dynamics and its control on the stable oxygen isotopic composition of precipitation in the Late Cenozoic. Journal of Geophysical Research: Atmospheres, 129(10), e2024JD040. [https://doi.org/10.1029/2024JD040748](https://doi.org/10.1029/2024JD040748)

1. Boateng, D. and Mutz, S. G. (2023). pyESD: An open-source Python framework for empirical-statistical downscaling of climate information. Geoscientific Model Development. [https://doi.org/10.5194/gmd-16-6479-2023](https://doi.org/10.5194/gmd-16-6479-2023)

1. Boateng, D., Mutz, S. G., Ballian, A., Meijers, M. J. M., Methner, K., Botsyun, S., Mulch, A., and Ehlers, T. A. (2023). The effects of diachronous surface uplift of the European Alps on regional climate and the oxygen isotopic composition of precipitation. Earth System Dynamics. [https://doi.org/10.5194/esd-14-1183-2023](https://doi.org/10.5194/esd-14-1183-2023)

1. Sacek V., Mutz S.G., Ehlers T.A., Bicudo T.C., de Almeida R.P. (2023). Amazonian paleoenvironments resulted from coupled geodynamic, paleoclimate and sea-level interactions. Earth and Planetary Science Letters. [https://doi.org/10.1016/j.epsl.2023.118033](https://doi.org/10.1016/j.epsl.2023.118033)

1. Mutz S.G. and Aschauer J. (2022). Empirical Glacier Mass-Balance Models for South America. Journal of Glaciology. [https://doi.org/10.1017/jog.2022.6](https://doi.org/10.1017/jog.2022.6)

1. Ring, S. J., Mutz, S. G., Ehlers, T. A. (2022). Cenozoic proxy constraints on Earth system sensitivity to greenhouse gases. Paleoceanography and Paleoclimatology, 37, e2021PA004364. [https://doi.org/10.1029/2021PA004364](https://doi.org/10.1029/2021PA004364)

1. Sharma H., Mutz S.G., Ehlers T.A. (2022). The effects of global Cenozoic climate change on frost cracking. Earth Surface Dynamics. [https://doi.org/10.5194/esurf-10-997-2022](https://doi.org/10.5194/esurf-10-997-2022)

1. Botsyun S., Ehlers T.A., Koptev A., Böhme M., Methner K., Risi C., Stepanek C., Mutz S.G., Werner M., Boateng D., Mulch A. (2022). Middle Miocene climate and stable oxygen isotopes in Europe based on numerical modeling. Paleoceanography and Paleoclimatology, 37, e2022PA004442. [https://doi.org/10.1029/2022PA004442](https://doi.org/10.1029/2022PA004442)

1. Botsyun S., Mutz S.G., Ehlers T.A., Scherrer D., Xun W., Schmidt B. (2022). Influence of large-scale atmospheric dynamics on Late Cenozoic precipitation seasonality of the Tibetan Plateau and Central Asia. Journal of Geophysical Research – Atmospheres. [https://doi.org/10.1029/2021JD035810](https://doi.org/10.1029/2021JD035810)

1. Mutz S.G., *Scherrer S., *Muceniece I., Ehlers T.A., (2021). Twenty-first Century Regional Temperature Response in Chile Based on Dynamical Empirical-Statistical Downscaling . Climate Dynamics. [https://doi.org/10.1007/s00382-020-05620-9](https://doi.org/10.1007/s00382-020-05620-9)

1. Wang X., Schmidt B., Otto M., Ehlers T.A., Mutz S.G., Botsyun S., Scherer D. (2021). Sensitivity of Water Balance in the Qaidam Basin to the Mid-Pliocene Climate. Journal of Geophysical Research – Atmospheres. [https://doi.org/10.1029/2020JD033965](https://doi.org/10.1029/2020JD033965)

1. Mohadjer S., Mutz S.G., Kemp M, Gill S., Ischuk A., Ehlers T.A. (2021). Using paired teaching for earthquake education in schools. Geoscience Communication. [https://doi.org/10.5194/gc-4-281-2021](https://doi.org/10.5194/gc-4-281-2021)

1. Krsnik E., Methner K., Campani M., Botsyun S., Mutz S.G., Ehlers T.A., Kempf O., Fiebig J., Schlunegger F., Mulch A. (2021). Miocene high elevation in the Central Alps. Solid Earth. [https://doi.org/10.5194/se-12-2615-2021](https://doi.org/10.5194/se-12-2615-2021)

1. Botsyun S., Ehlers T.A., Mutz S.G., Methner K., Krsnik E., Mulch A, (2020). Opportunities and Challenges for Paleoaltimetry in Small Orogens. Geophysical Research Letters. [https://doi.org/10.1029/2019GL086046](https://doi.org/10.1029/2019GL086046)

1. Mutz S.G. and Ehlers T.A., (2019). Detection and Explanation of Spatiotemporal Patterns in Late Cenozoic Palaeoclimate Change Relevant to Earth Surface Processes. Earth Surface Dynamics. [https://doi.org/10.5194/esurf-7-663-2019](https://doi.org/10.5194/esurf-7-663-2019)

1. Paeth H., Steger C., Li J., Pollinger F., Mutz S.G., Ehlers, T.A., (2019). Comparison of Climate Change from Cenozoic surface uplift and glacial-interglacial episodes in the Himalaya-Tibet region: Insights from a regional climate model and proxy data. Global and Planetary Change. [https://doi.org/10.1016/j.gloplacha.2019.03.005](https://doi.org/10.1016/j.gloplacha.2019.03.005)

1. Mutz S.G., Ehlers T.A., Werner M., Lohmann G., Stepanek C., Li J., (2018). Estimates of Late Cenozoic climate change relevant to Earth surface processes in tectonically active orogens. Earth Surface Dynamics. [https://doi.org/10.5194/esurf-6-271-2018](https://doi.org/10.5194/esurf-6-271-2018)

1. Mohadjer S., Ehlers T.A., Bendick R., Mutz S.G., (2017). Review of GPS and Quaternary fault slip rates in the Himalaya-Tibet orogen, Earth Science Reviews. [https://doi.org/10.1016/j.earscirev.2017.09.005](https://doi.org/10.1016/j.earscirev.2017.09.005)

1. Li J., Ehlers T.A., Werner M., Mutz S.G., Steger C., Paeth H. (2017). Late quaternary climate, precipitation δ 18O, and Indian monsoon variations over the Tibetan Plateau. Earth and Planetary Science Letters. [https://doi.org/10.1016/j.epsl.2016.09.031](https://doi.org/10.1016/j.epsl.2016.09.031)

1. Mutz S.G., Ehlers T.A., Li J., Steger C., Paeth H., Werner M., Pouslen C. (2016). Precipitation δ18O over the Himalaya-Tibet Orogen from ECHAM5-wiso Simulations: Statistical Analysis of Temperature, Topography and Precipitation. Journal of Geophysical Research – Atmospheres. [https://doi.org/10.1002/2016JD024856](https://doi.org/10.1002/2016JD024856)

1. Li J., Ehlers T.A., Mutz S.G., Steger C., Paeth H., Werner M., Poulsen C., Feng R. (2016). Modern precipitation δ18O and trajectory analysis over the Himalaya-Tibet Orogen from ECHAM5-wiso simulations. Journal of Geophysical Research – Atmospheres. [https://doi.org/10.1002/2016JD024818](https://doi.org/10.1002/2016JD024818)

1. Mutz S.G., Paeth H., Winkler S. (2015). Modelling of future mass balance changes of Norwegian glaciers by application of a dynamical-statistical model. Climate Dynamics. [https://doi.org/10.1007/s00382-015-2663-5](https://doi.org/10.1007/s00382-015-2663-5)


## Data and Monographs

1. Mutz S.G. and Ehlers T.A., (2023). Simulated Geomorphically Relevant Palaeoclimate Variables for the Late Cenozoic (from Mutz and Ehlers, 2019). Zenodo. [https://doi.org/10.5281/zenodo.8018119](https://doi.org/10.5281/zenodo.8018119)

1. Mutz S.G., Ehlers T.A., Werner M., Lohmann G., Stepanek C., Li J., (2023). Palaeoclimate Simulations for the Late Cenozoic (from Mutz et al. 2018). Zenodo. [https://doi.org/10.5281/zenodo.8018020](https://doi.org/10.5281/zenodo.8018020)

1. Mohadjer S., Mutz S.G., Kemp M. (2017). Journey to the Center of the Earth: Earth’s interior and plate tectonics, episode 1, Earthquake education, TIB. [https://doi.org/10.5446/47600](https://doi.org/10.5446/47600)

1. Mohadjer S., Mutz S.G., Drews R., Nettesheim M. (2017). Soft rocks and hard liquids: Properties of Earth materials, episode 3, Earthquake education, TIB. [https://doi.org/10.5446/47700](https://doi.org/10.5446/47700)

1. Mohadjer S., Mutz S.G., Amey R. (2017). Do you know your faults? Plate motions and faults, episode 4, Earthquake education, TIB. [https://doi.org/10.5446/47701](https://doi.org/10.5446/47701)

1. Mohadjer S., Mutz S.G., Mitchell L. (2017). What causes that Rock’n’Roll? The earthquake machine, episode 5, Earthquake education, TIB. [https://doi.org/10.5446/47702](https://doi.org/10.5446/47702)

1. Mohadjer S., Mutz S.G., Starke J. (2017). Rocking, rolling and bouncing: How do earthquakes move the Earth?, episode 6, Earthquake education, TIB. [https://doi.org/10.5446/47703](https://doi.org/10.5446/47703)

1. Mohadjer S., Mutz S.G., Nettesheim M., Drews R. (2017). Flow with the sand: Introduction to soil liquefaction, episode 7, Earthquake education, TIB. [https://doi.org/10.5446/47704](https://doi.org/10.5446/47704)

1. Mohadjer S., Mutz S.G., Kemp M., Gill S. (2017). On shaky ground: Structural hazards during earthquakes (Part 1), episode 9, Earthquake education, TIB. [https://doi.org/10.5446/47706](https://doi.org/10.5446/47706)

1. Mohadjer S., Mutz S.G., Gill S., Kemp M. (2017). On shaky ground: Structural hazards during earthquakes (Part 2), episode 10, Earthquake education, TIB. [https://doi.org/10.5446/47707](https://doi.org/10.5446/47707)

1. Mutz S.G. (2015). Dynamic Statistical Modelling of Climate-Related Mass Balance Changes in Norway. Universität Würzburg, Würzburg (Germany).


## Conference Presentations/Abstracts (selected)

1. Mohadjer S, Ergün G, Mutz S.G., Schneider M., Schürmann T., Pelzer M., Dietrich P. (2025) Non-Expert Understanding of Hazard Maps: An Eye-Tracking Study. EGU GA 2025.

1. Mutz S.G. (2025) The Effect of High-Mountain Asia Topography on Northern Hemisphere Atmospheric Flow. EGU GA 2025.

1. Boateng D., Mutz S.G. (2024) African monsoon changes in the Late Cenozoic from the climate modelling perspective. EGU GA 2024. Advertised Session Highlight.

1. Petrie E., Mutz S.G. (2024) Reflecting on the use of Generative AI in Higher Education Teaching & Learning. EGU GA 2024.

1. Gross E.S., Frick M., Norden B., Mutz S.G., Fuchs S. (2024) Regional effects of paleoclimate history on the subsurface temperature distribution in Germany. EGU GA 2024.

1. Ballian A., Meijers M.M.J., Cojan I., Huygue D., Methner K., Boateng D., Mutz S.G., Kurz W., Krsnik E., Zwingmann H., Rolland Y., Ehlers T.A., Fiebig J., Mulch A. (2024) Stable isotope paleoaltimetry reveals Early to Middle Miocene along-strike elevation differences of the European Alps. EGU GA 2024.

1. Mutz S.G., Boateng D. (2023) pyESD: An open-source Python framework for empirical-statistical downscaling of climate information. EGU GA 2023.

1. Boateng D., Mutz S.G., Ehlers T.A. (2023) The influence of North Atlantic Oscillation on oxygen and hydrogen stable isotopes in precipitation of the Late Cenozoic: implications on paleoenvironment reconstructions. EGU GA 2023.

1. Sedhu-Madhavan A., Mutz S.G., Boateng D., Ehlers T.A. (2023) A model-based exploration of mid-Holocene anti-phase climate variations in the Central Andes. EGU GA 2023.

1. Eizenhöfer P.R., McQuarrie N, Ghoshal S., Mutz S.G., Ehlers T.A. (2023) Drivers of Topography in Fold-thrust Belts: A Perspective from Central Nepal. EGU GA 2023.

1. Ring S., Mutz S.G., Ehlers T.A. (2022) Earth system sensitivity constrained from Cenozoic global cooling. ICP14 Bergen.

1. Mutz S.G., Boateng D., Mohadjer S. (2022) INTEGRATE: A higher-education teaching package for climate science. EGU GA 2022. Invited as Solicited Speaker.

1. Mutz S.G. and Ehlers T.A. (2022). How the co-evolution of major mountain ranges affects global climate. EGU GA 2022. Advertised Session Highlight.

1. Boateng D., Mutz S.G. and Ehlers T.A. (2022). How would the eastward propagation of surface uplift in the Alps affect regional climate and isotopic composition of precipitation? EGU GA 2022.

1. Beer A., Krumrein N., Mutz S.G., Rink, G.M. and Ehlers T.A. (2022). Spatial rockfall susceptibility prediction from rockwall surface classification. EGU GA 2022.

1. Toy V., Abe S., Bons P, Buckley S.J., Deckert H., Fenske S., Kirilova M., Lewis C., Mutz S.G., Owin J.,  Sachau T., Schuck B., and Seelos P.  (2021). A blended learning approach to structural field mapping: combining local geology, virtual geology, and web-based tools. EGU GA 2021.

1. Mutz S.G. and Ehlers T.A. (2020). On the Synergistic Climatic Effects of Covarying Major Mountain Range Topographies. EGU GA 2020.

1. Mohadjer S, Mutz S.G., Kemp M., Gill S., Ischuk A., Ehlers T.A. (2020) Paired teaching approach to earthquake education: a cross-country comparison between Dushanbe, Tajikistan and London, United Kingdom. EGU GA 2020.

1. Schmidt B, Wang X., Mutz S.G., Botsyun S., Ehlers T.A. Scherer D. (2020) Changes in water balance of the Qaidam Basin from Pliocene to present day. EGU GA 2020.

1. Mutz S.G., Scherrer S., Muceniece I., Ehlers T.A. (2019). Towards a dynamic hybrid of parametric and non-parametric empirical downscaling models for climate in Chile. AK Klima 2019.

1. Ehlers T.A., Densmore A.L., Schaller M., Adams B.A., Ershadi M., Mutz S.G. (2019). Trends and Aberrations in the Measured Fluvial Erosion Response to Global Paleoclimate Change. EGU GA 2019.

1. Mutz S.G. and Ehlers T.A. (2018). Detecting and Quantifying the Synergistic Effects of Covarying Major Mountain Range Topographies on Regional Climate. AK Klima 2018.

1. Mutz S.G. and Ehlers T.A. (2018). A Quantitative Assessment of Differences between Simulated Pre-Industrial and Late Cenozoic Palaeoclimates with Regard to Earth Surface Processes. AK Klima 2018.

1. Botsyun S., Ehlers T.A., Mutz S.G., Werner M., Stepanek C. (2018) Neogene aridiﬁcation, precipitation δ18O, and trajectory analysis over Central Asia from paleoclimate simulations. EGU GA 2018.

1. Mutz S.G. and Ehlers T.A. (2018) Late Cenozoic Climate Change and Potential Impacts on Denudation at Different Orogens. EGU GA 2018 .

1. Mohadjer S., Mutz S.G., Amey R., Drews R., Kemp M., Kloos P., Mitchell L., Nettesheim M., Gill S., Starke J., Ehlers T.A. (2018) Using Paired Teaching for Earthquake Education in Schools. EGU GA 2018.

1. Mutz S.G. and Ehlers T.A. (2017). Late Cenozoic Climate Change and its Implications on the Denudation of Orogen Syntaxes. EGU GA 2017. Advertised Session Highlight.

1. Ehlers, T.A., Schaller M., Mutz S.G. (2017) Climate Controls on European Fluvial Denudation over Glacial-Interglacial Cycles. EGU GA 2017

1. Mutz S.G., Ehlers T.A., Li J., Werner M., Stepanek C., Lohmann G. (2016) Investigating Cenozoic climate change in tectonically active regions with a high-resolution atmospheric general circulation model (ECHAM5). EGU GA 2016.

1. Mutz S.G., Paeth H., Winkler S. (2011) Statistical modelling of climate-related future mass balance changes of maritime mountain glaciers in Norway. EGU GA 2011

1. Mutz S.G., Paeth H., Winkler S. (2010) Impact of large-scale circulation modes, regional temperature and precipitation on the mass balance of South Norwegian glaciers. IGS Nordic Branch Meeting 2010

1. Mutz S.G., Paeth H., Winkler S. (2009) Dynamisch-Statistische Modellierung der Klimabedingten Gletschermassenveränderungen in  den Mittleren Breiten. AK Klima 2009
