---
title: "Service"
---

# Professional Societies and Development of Others

| Years | Project or Organisation | Role |
| :- | :----- | :--- |
| 2026 | [Fortran-lang](https://fortran-lang.org/) work placement | Mentor |
| 2025 | [Fortran-lang](https://fortran-lang.org/) at [Google Summer of Code](https://summerofcode.withgoogle.com/) | Mentor |
| 2024 -- | [Exascale Computing for Earth, Environmental, and Sustainability Solutions](https://www.exageo.org/) (ExaGEO) | Manager / Executive Committee Member |
| 2024 -- | [Earth System Modelling and Artificial Intelligence](https://sages.ac.uk/research/fora/earth-system-modelling-artificial-intelligence-esm-ai/) (SAGES) | Steering Committee Member |
| 2023 -- | [Earth System Dynamics](https://www.earth-system-dynamics.net/) Editorial Board | Associate Editor |
| 2022 -- | [Geoscience Communication](https://www.geoscience-communication.net/) Editorial Board | Associate Editor |
| 2022, 2023 | [EGU’s mentoring programme](https://www.egu.eu/outreach/mentoring/)| Mentor |
| 2018 -- | Professional Funding Bodies (e.g., Serrapilheira Institute, Software Sustainability Institute) | Grant and Candidate Reviewer |
| 2009 -- | [European Geosciences Union](https://www.egu.eu/) | Member and Contributor (convener, reviewer, and more) |
| 2009 -- | Peer-Review Journals (e.g., *Geophysical Research Letters*, *Geoscientific Model Development*) | Article Reviewer |



# External Event Organisation for the Development of Others

| Years | Event | Role |
| :- | :--------- | :--- |
| 2026 | “Teacher-Scientist Networking Event" (networking event at EGU GA) | Co-organiser |
| 2026 | “Fortran for Earth and Planetary Sciences" (networking event at EGU GA) | Organiser |
| 2026 | “Get your writing right: A hands-on, participatory workshop to help improve writing skills” (workshop at EGU GA) | Co-convener |
| 2026 | “How to publish my geoscience communication work: A hands-on, participatory workshop.” (workshop at EGU GA) | Co-convener |
| 2025 | “EGU's Teacher-Scientist Pairing Scheme: Extreme Climate Events - Preparing for Disaster” (live teachingevent at EGU GA) | Organiser |
| 2025 | “Scientists and School Teachers Matchmaking Event ” (live teachingevent at EGU GA) | Organiser |
| 2025 | “How to communicate uncertainty to non-expert audiences?” (networking event at EGU GA) | Organiser |
| 2025 | “Contributing to best-practice in geoscience communication by publishing" (workshop at EGU GA) | Co-convener |
| 2024 | "How do I make my geoscience communication publishable?” (workshop at EGU GA) | Co-convener |
| 2022 | “Biogeomorphology and Earth surface dynamics across scales: from long-term landscape evolution to short-term interactions and future applications” (conference session at EGU GA) | Co-convener |
| 2018 | “Actio-Reactio; from subducting slabs to shaping the surface” (conference session at EGU GA) | Co-convener |
| 2016 | "The Sustainable Development Goals: Strategies for Eradicating Global Poverty” (workshop at EGU GA) | Co-convener |



# University Service (Only Recent; Selected)

| Years | Project or Organisation | Role |
| :- | :--------- | :--- |
| 2025 -- | [Climate and Environmental Science MSc](https://www.gla.ac.uk/postgraduate/taught/climateenvironmentalscience/) programme | Programme Lead and Developer |
| 2025 -- | GenAI strategy group for learning and teaching at the College of Science and Engineering | Member |
| 2024 -- | *Earth, Climate and Biosphere Dynamics* Research Cluster | Co-Lead |
| 2024 -- | [ExaGEO](https://www.exageo.org/) doctoral training programme | Manager and Co-Investigator |
| 2024 -- | *Maths/Stats meets GeoX*, interdepartmental initiative | Co-Lead |
| 2024 | Environmental Futures: Sustinable Systems MSc programme | Co-Lead |
| 2023 -- | Department website (*School for Geographical & Earth Sciences*) | Content manager |
| 2015 -- 2022 | HPC software infrastructure for Earth system modelling | Maintainer |
